### ISSUE TITLE
[FR] Provide Metadata for TV Libraries

### ISSUE THREAD

**Issue by thezak48** [ThePornDatabase/Jellyfin.Plugin.ThePornDB#62]
Due to Whisparr v2 now using a Sonarr base it organises scenes like TV Shows, currently the plugin only provides metadata for Movie libraries in Jellyfin. If a Movie library is used for scenes organised by Whisparr then they all get clubbed together resulting in a massive mess.

To solve this the plugin is required to provide metadata for TV Show libraries in Jellyfin

**Comment by DirtyRacer1337** [comment]
I didn't used any of that (and not going to), doesn't seem like plugins problem, https://jellyfin.org/docs/general/server/media/movies

**Comment by Druidblack** [comment]
I have the same problem. Due to the fact that the shows are in the Cinema section, they are combined into one movie and the data for each episode is not loaded.
It is necessary that the plugin has access to the tv show section.

**Comment by Darklyter** [comment]
You have dashes in your filenames, don't you?  If the directory name is part of the filename as well, Jellyfin will see it as "versions" of a common movie.  Here's our boilerplate on the subject:

Jellyfin uses a  -  separator for the filename.  Because of that, if you use the "standard scene naming" format of {SITE} - {DATE} - {TITLE} then it will parse out the first section (the sitename) as the name of the video/movie.  If that name is the same as the folder, then it simply thinks it's a version of that movie.

What that means is that if you have multiple files in a folder named /The Best Site Ever and your files are named The Best Site Ever - YYYY-MM-DD - * then it will see every file as a variant of the same video/movie (like you would if you had 720p/1080p/4k versions of the same video).  When this happens it will group them together into one item, with possibly hundreds of different "versions".

To get around this you have three simple options.
The first is to use subdirectories for each file, which will break that match service in JF.
The second is to use something different in the directory name that you have in your files.  /TBSE/The Best Site Ever - YYYY-MM-DD - * will not match, and all files will be seen as unique...  no combining.
The third is to use an alternate naming scheme for your videos.  For example simply using {SITE} {DATE} {TITLE} will get around it due to no separator, the match will not happen and all files will be seen as unique.  You could also use a different separator of your choice, such as an underscore or period instead of  - .
